### ISSUE TITLE
Server Error on Startup with Vampirism/Issue with Stone Mason in Minecolonies

### ISSUE THREAD

**Issue by Dragonsissiy** [MaxBogomol/WizardsReborn#1] opened 2023-10-25 00:55 UTC
Just wanted to let you know that the most recent version of your mod (0.0.4) has an error with Vampirism (current version 1.9.3) on a server. 
It works in the client version of minecraft.
Specifically your mod is part of the Minecolonies Dimensional Adventures pack, and it also currently breaks the Stone Mason from Minecolonies in most versions of that mod. The stone mason is unable to use or learn the recipies it's supposed to use.

Anywho, here is the error I got with your mod and Vampirism. (Also we're enjoying your mod regardless so thank you for that.)

![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/46a4e2a3-d9ea-46fa-8f89-5d53a1255386)

**Comment by MaxBogomol** [comment] 2023-10-25 02:31
Does the server work without Wizard's Reborn?
The screenshot just shows a registration error in vampirism and has nothing to do with Wizard's Reborn.

**Comment by warmer-autumn** [comment] 2023-10-27 00:10
I had a similar error trying to start this mod serverside. Disabling Wizard's Reborn, my server started normally.

Before disabling:
[before_wiz_re.log](https://github.com/MaxBogomol/WizardsReborn/files/13183692/before_wiz_re.log)

After:
[latest.log](https://github.com/MaxBogomol/WizardsReborn/files/13183703/latest.log)

**Comment by Dragonsissiy** [comment] 2023-10-27 02:17
> Does the server work without Wizard's Reborn? The screenshot just shows a registration error in vampirism and has nothing to do with Wizard's Reborn.

I'm so sorry, I got busy and forgot I made this post! 
For some reason, with that version of wizards reborn (0.0.4) in this mod pack it would cause vampirism 1.9.3 to have that error I posted.
The previous version of wizards reborn (0.0.3) works with vampirism 1.9.3.

Also though the wizards reborn version 0.0.3 causes the Stone Mason from Minecolonies version 1.1.240 all the way to the current beta version 1.1.265 to be unable to crash any of its normal recipes. In fact JEI wont even show stone mason as capable of making any recipies it should normally. With wizards reborn removed it starts working.

**Comment by Dragonsissiy** [comment] 2023-10-27 02:17
didn't mean to close this. It's been a rough week lol

**Comment by MaxBogomol** [comment] 2023-10-27 19:33
I fixed the error with starting the server

Сan you tell me more about Stone Mason?

**Comment by Dragonsissiy** [comment] 2023-10-28 02:35
sure! let me get you a couple screenshots. So the stone mason in minecolonies is supposed to be able to make stone related recipes both from regular minecraft and from the mod dependencies it has.  

![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/e5884d95-1dc2-47f3-ba5e-789d5c8f8aa3)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/4d9ed9f8-c6f1-4196-b77e-833cf513f32b)
This is how the stonesmelter looks, but at the top there should be a section also for the stone mason. It should show that the stone mason can make stone bricks just as the player would. However, if you go to the stone mason and try to teach it the recipe it says that it can't because it doesn't match what the building can make. 

Normally with wizards reborn not installed in the mod pack, the stone mason can learn the recipe again and shows up at the top tabs on things it can make. This is true of ALL recipes for the stone mason. I haven't see that issue yet with the other buildings in minecolonies, but very much that one. I also tested wizards reborn with the minecolonies 1.1.240-release version and the most recent version 1.1.265-beta. Let me know if you need more examples! 

Also thank you for fixing that issue with vampirism so quickly!

**Comment by MaxBogomol** [comment] 2023-10-28 13:36
Looks like this is a conflict with some other mods.
It’s just that everything works for me, the stone mason and others tab exists.
I will release a bugfix update soon.
If the error occurs again, please tell me!

**Comment by Dragonsissiy** [comment] 2023-10-28 19:25
Gotcha, just so you know if you want to test better since I don't think I mentioned it before. The mod pack we've been using is Minecolonies Dimensional Adventures if you wanted to see the conflict I was seeing. Thank you much for the help!

**Comment by MaxBogomol** [comment] 2023-10-29 08:11
I installed the latest version of Minecolonies Dimensional Adventures and all tabs are present
![image](https://github.com/MaxBogomol/WizardsReborn/assets/90563409/d78dcd36-1c10-4cb7-aedf-54873b548983)

**Comment by Dragonsissiy** [comment] 2023-10-29 18:46
I'm not sure what's different with ours then. 4 of us are having this issue and a couple others on the minecolonies dimensions discord as well :( We have the most recent version as well which is 1.9.5 i believe

**Comment by Dragonsissiy** [comment] 2023-10-29 18:47
server side only mods i have are severcore, spark, connectivity, and smoothchunk. I believe the server pack of the mod installs neruina as well.

**Comment by Dragonsissiy** [comment] 2023-10-31 01:12
I wanted to show you the list of mods we're using. I just tested updating a few mods including wizards reborn and still couldn't use the stone mason. i removed wizards reborn and was able to use it again.

![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/e285a5ba-4e1c-4306-98a6-6c4a52b26bce)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/9371e0f1-e090-4109-b0cc-4f9ab7cfcac4)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/6ce4f07e-341b-47cb-95d8-745796eab442)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/f0d1ebf3-20ae-4c79-a36c-74510516a90d)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/8ab74323-18e1-4ba2-b824-4cd6109ac144)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/3c63844c-53cb-4145-b70c-95d02fb5c68a)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/e5c00b79-df5c-4a3d-856b-88392e0c4d6e)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/cec19b7f-6b4a-4775-ad28-c0e985de4bbd)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/0858ad3b-df07-44c2-9a34-05d1409c94f0)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/5dd9c317-b957-407c-bd48-b3a64e0fad9d)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/c6d542e1-724e-46c4-b148-7a7c92a6aa20)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/68d8a93e-dd06-47cf-805d-80f774d48747)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/557082a2-af3c-45f9-a045-c4c82e6c128c)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/a270437c-7539-44e3-ba61-12ad26ea814c)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/60621847/0056cdc8-c91a-40cc-ba32-3abca4391af6)

**Comment by Cadek2002** [comment] 2023-11-11 05:33
Moving this from the mine colonies discord: This is a cascading tag issue caused by arcane_wood_stairs breaking Minecraft:stairs/wooden then Minecraft:stairs and finally minecolonies:stonemason_product.

Here is the relevant segment from startup logs with just those two mods loaded:

`[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [wizards_reborn:arcane_wood_stair (from wizards_reborn-1.20.1-0.0.6.jar)] as it is missing following references: wizards_reborn:arcane_wood_stair (from wizards_reborn-1.20.1-0.0.6.jar)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#minecraft:wooden_stairs (from minecolonies-1.20.1-1.1.240-RELEASE.jar)] as it is missing following references: #minecraft:wooden_stairs (from minecolonies-1.20.1-1.1.240-RELEASE.jar)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)] as it is missing following references: #wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#forge:fence_gates/wooden (from forge-1.20.1-47.2.0-universal.jar), #wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)] as it is missing following references: #forge:fence_gates/wooden (from forge-1.20.1-47.2.0-universal.jar), 
	#wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)
[22:55:45] [Worker-Main-3/ERROR]: Couldn't load tag [#wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)] as it is missing following references: #wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)
[22:55:45] [Worker-Main-3/ERROR]: Couldn't load tag [#forge:fence_gates/wooden (from forge-1.20.1-47.2.0-universal.jar), #wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)] as it is missing following references: #forge:fence_gates/wooden (from forge-1.20.1-47.2.0-universal.jar), 
	#wizards_reborn:arcane_wood_fence_gate (from wizards_reborn-1.20.1-0.0.6.jar)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#minecraft:wooden_stairs (from vanilla)] as it is missing following references: #minecraft:wooden_stairs (from vanilla)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#minecraft:stairs (from minecolonies-1.20.1-1.1.240-RELEASE.jar)] as it is missing following references: #minecraft:stairs (from minecolonies-1.20.1-1.1.240-RELEASE.jar)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#minecraft:stairs (from minecolonies-1.20.1-1.1.240-RELEASE.jar)] as it is missing following references: #minecraft:stairs (from minecolonies-1.20.1-1.1.240-RELEASE.jar)
[22:55:45] [Worker-Main-11/ERROR]: Couldn't load tag [#minecolonies:stonemason_product (from minecolonies-1.20.1-1.1.240-RELEASE.jar)] as it is missing following references: #minecolonies:stonemason_product (from minecolonies-1.20.1-1.1.240-RELEASE.jar)`

The mod 'Load my f***ing tags' (yes that's the mod name) adds a failsafe to the behavior and fixes this bug (though that mod also happens to not play nice with a series of others for reasons I have not figured out yet)

**Comment by MaxBogomol** [comment] 2023-11-11 09:26
I fix tags

**Closed by MaxBogomol** 2023-11-11 09:26 UTC
